:- dynamic(playerPos/2).
:- dynamic(player/9).
:- dynamic(opened/1).
:- dynamic(started/1).
:- dynamic(inBattle/1).
:- dynamic(enemy/7). 
:- dynamic(enemySpecialAttack/1). 
:- dynamic(specialAttackCount/1). 
:- dynamic(meetEnemy/1).
:- dynamic(chancetorun/1).
:- dynamic(boss/5).
:- dynamic(inShop/1).
:- dynamic(playerInventory/1).
:- dynamic(mapHeight/1).
:- dynamic(mapWidth/1). 
:- dynamic(questPos/2).
:- dynamic(shopPos/2).
:- dynamic(gateUpper/2).
:- dynamic(gateLower/2).
:- dynamic(bossPos/2).
:- dynamic(quest/3).
